services:
  mysql:
    container_name: directus-mysql
    image: mysql:9.3.0
    restart: unless-stopped
    volumes:
      - ./backend/mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - directus-network

  cache:
    container_name: directus-redis
    image: redis:alpine3.21
    restart: unless-stopped
    networks:
      - directus-network

  directus:
    container_name: directus
    image: tractr/directus-sync:11.7.2
    user: node
    restart: unless-stopped
    volumes:
      - ./backend/directus/data/uploads:/directus/uploads
      - ./backend/directus/data/extensions:/directus/extensions
      - ./backend/directus/data/templates:/directus/templates
    depends_on:
      - cache
      - mysql
    environment:
      SECRET: ${DIRECTUS_SECRET_PHRASE}

      DB_CLIENT: "mysql"
      DB_HOST: "mysql"
      DB_PORT: "3306"
      DB_DATABASE: ${MYSQL_DATABASE_NAME}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_SSL: false

      CACHE_ENABLED: "true"
      CACHE_AUTO_PURGE: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://cache:6379"

      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}

      PUBLIC_API_URL: ${PUBLIC_API_URL}
      PUBLIC_API_TOKEN: ${PUBLIC_API_TOKEN}

      CORS_ENABLED: ${CORS_ENABLED}
      CORS_ORIGIN: ${CORS_ORIGIN}

      SESSION_COOKIE_TTL: ${SESSION_COOKIE_TTL}
      SESSION_COOKIE_SECURE: ${SESSION_COOKIE_SECURE}
      SESSION_COOKIE_SAME_SITE: ${SESSION_COOKIE_SAME_SITE}
      SESSION_COOKIE_NAME: ${SESSION_COOKIE_NAME}

      LOG_LEVEL: ${DIRECTUS_LOG_LEVEL}
    networks:
      - directus-network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: ${BUILD_TARGET}
      args:
        - VITE_DIRECTUS_URL=${PUBLIC_API_URL}
        - VITE_CREATE_SNAPSHOT_FLOW_ID=${CREATE_SNAPSHOT_FLOW_ID}
    volumes:
      - ./frontend:/app:cached
      - ./frontend/node_modules:/app/node_modules
      - ./backend/nginx/data/logs:/var/log/nginx
    environment:
      - NODE_ENV=${BUILD_TARGET}
    depends_on:
      - directus
    networks:
      - directus-network

  nginx:
    container_name: nginx
    image: nginx:1.28-bookworm-otel
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend/nginx/config:/etc/nginx/conf.d
      - ./backend/nginx/ssl:/etc/letsencrypt
      - ./backend/nginx/data/logs:/var/log/nginx
    depends_on:
      - directus
      - frontend
    networks:
      - directus-network

networks:
  directus-network:
    name: directus-network